import { readFile, writeFile, mkdir, copyFile, readdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { root, loadPalettes, variables, pilotfox, loadPilotfox, variantNames } from "./palettes.mjs";

const rule = (selector, values) => `${selector} {\n${Object.entries(values).map(([key, value]) => `  ${key}: ${value};`).join("\n")}\n}`;
const read = async file => (await readFile(path.join(root, file), "utf8")).replace(/^\uFEFF/, "");
export async function generate() {
  const palettes = await loadPalettes();
  const shared = await read("scripts/shared.css");
  const licenses = await Promise.all(["LICENSE", "licenses/Nightfox-MIT.txt", "licenses/Monaspace-OFL.txt", "licenses/Mona-Sans-OFL.txt"].map(read));
  const fonts = JSON.parse(await read("fonts/manifest.json"));
  const fontCss = await Promise.all(fonts.map(async font => {
    const bytes = await readFile(path.join(root, "fonts", font.file));
    if (createHash("sha256").update(bytes).digest("hex") !== font.sha256) throw new Error(`Font checksum mismatch: ${font.file}`);
    return `@font-face {\n  font-family: "${font.family}";\n  font-style: ${font.italic ? "italic" : "normal"};\n  font-weight: ${font.weight};\n  font-display: swap;\n  src: url("data:font/woff2;base64,${bytes.toString("base64")}") format("woff2");\n}`;
  }));
  const rules = palettes.map(p => {
    const mode = p.light ? "light" : "dark";
    const defaultSelector = ["dayfox", "nightfox"].includes(p.name) ? `body.theme-${mode},\n` : "";
    return rule(`${defaultSelector}body.theme-${mode}.fox-${mode}-${p.name}`, variables(p));
  });
  // Pilotfox: captured Copilot app values layered over upstream Dayfox; uncaptured roles keep Dayfox values.
  const pilotfoxBase = variables(palettes.find(p => p.name === pilotfox.base));
  rules.splice(2, 0, rule(`body.theme-light.fox-light-${pilotfox.name}`, { ...pilotfoxBase, ...await loadPilotfox() }));
  return `/* Fox Suite. Generated by npm run build; edit scripts/ and palettes/ instead.\n * Original mappings: MIT. Nightfox palettes: MIT, James Simpson.\n * Embedded fonts: SIL OFL 1.1. Full license texts follow at the end.\n * Pilotfox: measured GitHub Copilot app colors from palettes/pilotfox.json.\n */\n\n${shared}\n\n${rules.join("\n\n")}\n\n${fontCss.join("\n\n")}\n\n/*\n${licenses.join("\n\n").replaceAll("*/", "* /")}\n*/\n`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.join(root, "scripts", "build.mjs")) {
  const css = await generate();
  if (process.argv.includes("--check")) {
    if (await read("theme.css") !== css) throw new Error("theme.css is stale; run npm run build.");
    console.log("theme.css is reproducible and current.");
  } else {
    await writeFile(path.join(root, "theme.css"), css);
    console.log(`Built Fox Suite: ${variantNames.length} variants, 6 embedded fonts, no network dependencies.`);
  }
  if (process.argv.includes("--package")) {
    const folder = path.join(root, "dist", "Fox Suite");
    const files = ["theme.css", "manifest.json", "LICENSE", "THIRD_PARTY_NOTICES.md", "README.md",     "preview.html", "screenshot.png", "licenses/Nightfox-MIT.txt", "licenses/Monaspace-OFL.txt", "licenses/Mona-Sans-OFL.txt", ...variantNames.map(name => `screenshots/${name}.png`)];
        const directories = ["licenses", "screenshots"];
        for (const directory of directories) await mkdir(path.join(folder, directory), { recursive: true });
    const inspect = async directory => {
      for (const entry of await readdir(directory, { withFileTypes: true })) {
        const fullPath = path.join(directory, entry.name);
        const relative = path.relative(folder, fullPath).split(path.sep).join("/");
        if (entry.isSymbolicLink() || (entry.isDirectory() ? !directories.includes(relative) : !files.includes(relative))) {
          throw new Error(`Unexpected existing package entry: ${relative}. Remove it explicitly before packaging.`);
        }
        if (entry.isDirectory()) await inspect(fullPath);
      }
    };
    await inspect(folder);
    for (const file of files) {
      await copyFile(path.join(root, file), path.join(folder, file));
    }
    console.log(`Manual-install package: ${folder}`);
  }
}
